.TH tSystemSound 3  "July 19, 2020" "the-libs" "theSuite Manual"

THIS MANPAGE IS A WORK IN PROGRESS!

.SH NAME
tSystemSound \- foo

.SH SYNOPSIS
.B #include <foo.h>

.SH DESCRIPTION
Description here

.SH CLASSES
.IP - 2
.BI "Class (int " &argc ", char " **argv ")"
.br
Class description

.SH SLOTS
.IP - 2
.BI "void slot (int " &argc ", char " **argv ")"
.br
Slot description
.IP - 2
.BI "void slot (int " &argc ", char " **argv ")"
.br
Slot description

.SH SIGNAL
.IP - 2
.BI "void signal (int " &argc ", char " **argv ")"
.br
Signal description
.IP - 2
.BI "void signal (int " &argc ", char " **argv ")"
.br
Signal description

.SH SEE ALSO
\fBthe-libs\fR(7)

.SH BUGS
See:
\%https://github.com/vicr123/the-libs/issues

.SH AUTHOR
\fBthe-libs\fP is created by
.MT vicr12345@\:gmail.com
Victor Tran
.ME
.PP
This manpage is written by
.MT daxuya.zumi+docs@\:protonmail.com
Zumi
.ME
